export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ROOT: '/',
  UNAUTHORIZED: '/unauthorized',
  USER_DASHBOARD: '/users',
  SIGNUP: '/signup',
  HOME: '/',
  MESSAGES: '/messages',
  CHILD_PROGRESS: '/progress',
  DAILY_ACTIVITIES: '/activities',
  PARENT_DASHBOARD: '/parent-dashboard',
  TEACHER_DASHBOARD: '/teacher-dashboard',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  PROFILE_CHANGE_PASSWORD: '/profile/change-password',
  REGISTER_INVITE: '/register/invite/:token',
} as const;
