export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/messages',
  ROOT: '/',
  UNAUTHORIZED: '/unauthorized',
  USER_DASHBOARD: '/users',
  HOME: '/',
  MESSAGES: '/messages',
  CHILD_PROGRESS: '/progress',
  DAILY_ACTIVITIES: '/activities',
  PARENT_DASHBOARD: '/parent-dashboard',
  TEACHER_DASHBOARD: '/teacher-dashboard',
  PROFILE: '/profile',
  PROFILE_DETAIL: '/profile/:id',
  PROFILE_EDIT: '/profile/edit',
  REGISTER_INVITE: '/register/invite/:token',
  CLASSES: '/classes',
  CLASS_DETAIL: '/classes/:id',
  presentation: '/presentation',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CHILDREN: '/children',
} as const;
