export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ROOT: '/',
  UNAUTHORIZED: '/unauthorized',
  USER_DASHBOARD: '/users',
  SIGNUP: '/signup',
  HOME: '/',
  CHILDREN: '/children',
  PROFILE: '/profile',
  PROFILE_DETAIL: '/profile/:id',
  PROFILE_EDIT: '/profile/edit',
  PROFILE_CHANGE_PASSWORD: '/profile/change-password',
  CLASSES: '/classes',
  CLASS_DETAIL: '/classes/:id',
  presentation: '/presentation',
  MESSAGES: '/messages',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  REGISTER_INVITE: '/invite/:token',
} as const;
